apiVersion: v2
name: redis-rdb-analyzer
description: A Helm chart for Redis RDB Analyzer - Kubernetes-native RDB file analysis tool
type: application
version: 1.0.0
appVersion: "v1.0"
keywords:
  - redis
  - rdb
  - analyzer
  - monitoring
  - kubernetes
maintainers:
  - name: naufaruuu
home: https://github.com/naufaruuu/redis-rdb-analyzer
sources:
  - https://github.com/naufaruuu/redis-rdb-analyzer
icon: https://redis.io/images/redis-white.png
