apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-rdb-analyzer.fullname" . }}
  labels:
    {{- include "redis-rdb-analyzer.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  POD_CACHE_DURATION: {{ .Values.config.pod_cache | quote }}
  MAX_RDB_SIZE: {{ .Values.config.max_rdb_size | quote }}
